#include<iostream>
using namespace std;//print 1 to n without using extra parameter ....
int fun(int x){  
    if(x==0)return 0;
    fun(x-1);
    cout<<x<<endl;
}
int main(){  // very very important concept...
    int x;   // reverse recursion process...
    cin>>x;     //1st call call call call .... then print print print print....
    fun(x);
}