#include<iostream>
#include<unordered_set>
using namespace std;
int main(){
    unordered_set<int>s;
    s.insert(1);
    s.insert(2); // it takes only "O(1) T.C" to search , insearch and delete...
    s.insert(3);
    s.insert(4);
    s.insert(5);
    s.insert(2);// it dosen't use repeated element...
    s.erase(3);// it is use to delete the sets...
    cout<<s.size()<<endl; // print the size of the sets...

    int target = 4;
    if(s.find(2)!=s.end())cout<<"exists"<<endl; // use to find the ele exists in sets or not ...
    else cout<<"Dosen't exists..."<<endl; // Or we can say search the ele...

    for(int ele : s){ // we use "for each loop" to print sets ele...
        cout<<ele<<" ";
    }
} 