#include <bits/stdc++.h>
using namespace std;
bool isSet(int n, int a){
    return (n & a); // it 0 or 1 like if 000100 then in decimal it is 1 and if 00000 then in decimal it is 0 so return as it is ...
}
int main(){
    int n; cin >> n;
    // check for the number n that its 2nd bit set or not ?
    //Method ...
    // Take the number which has only 2nd Bit Set and other are zero then take ans with n of that number 
    int a = (1 << 2);
    cout << isSet(n,a);

    // if i have to set the specific bit then just take "or" in place of "and" and do the same job ...
    // if i have to unset the specific bit then we use tilda (~) which actually reverse the number 10001 to 01110 and then take and with that number which i have to unset ...
    // if we have to check the total number of set bit in number then we can use  (__builtin_popcount(num)) for int...
    //   (__builtin_popcountll(num)) for long long numbers...
}